# Generated by Django 5.2.1 on 2025-07-15 06:28

import caption.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaptionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=caption.models.caption_directory_path)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('device', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
