# Generated by Django 5.2.1 on 2025-07-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caption', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captionresult',
            name='caption',
            field=models.TextField(),
        ),
    ]
