# Generated by Django 5.1.5 on 2025-04-28 01:05

import caption.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caption', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captionresult',
            name='image',
            field=models.ImageField(upload_to=caption.models.caption_directory_path),
        ),
    ]
