# Generated by Django 5.1.5 on 2025-04-28 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caption', '0002_alter_captionresult_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='captionresult',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='captionresult',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='captionresult',
            name='device',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='captionresult',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='captionresult',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
