# Generated by Django 5.2.1 on 2025-06-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caption', '0003_captionresult_author_captionresult_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captionresult',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
