# Generated by Django 5.2.1 on 2025-07-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caption', '0004_alter_captionresult_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captionresult',
            name='date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
