# Generated by Django 5.1.5 on 2025-02-22 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useracc', '0004_alter_user_is_staff_alter_user_profile_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
    ]
