# Generated by Django 5.1.5 on 2025-04-28 01:05

import useracc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useracc', '0006_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to=useracc.models.user_directory_path),
        ),
    ]
