# Generated by Django 5.2.1 on 2025-06-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useracc', '0007_alter_user_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(default='email', max_length=255),
        ),
    ]
