# Generated by Django 5.2.1 on 2025-06-04 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useracc', '0008_user_auth_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
