# Generated by Django 5.2.1 on 2025-06-20 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useracc', '0009_alter_user_profile_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auth_provider',
        ),
    ]
