# Generated by Django 5.2.1 on 2025-06-20 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useracc', '0010_remove_user_auth_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
